// <auto-generated />
using BusinessLookup.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BusinessLookup.Migrations
{
    [DbContext(typeof(BusinessLookupContext))]
    [Migration("20210403100139_NewDatabase")]
    partial class NewDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("BusinessLookup.Models.Restaurant", b =>
                {
                    b.Property<int>("RestaurantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Food")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Number")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("RestaurantId");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            RestaurantId = 1,
                            Food = "yeehaw",
                            Name = "first restaurant",
                            Number = "555"
                        },
                        new
                        {
                            RestaurantId = 2,
                            Food = "second",
                            Name = "second restaurant",
                            Number = "222"
                        },
                        new
                        {
                            RestaurantId = 3,
                            Food = "third",
                            Name = "third restaurant",
                            Number = "503"
                        });
                });

            modelBuilder.Entity("BusinessLookup.Models.Shop", b =>
                {
                    b.Property<int>("ShopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Goods")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Number")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ShopId");

                    b.ToTable("Shops");

                    b.HasData(
                        new
                        {
                            ShopId = 1,
                            Goods = "yeehaw",
                            Name = "first shop",
                            Number = "1900"
                        },
                        new
                        {
                            ShopId = 2,
                            Goods = "second",
                            Name = "second shop",
                            Number = "pdx"
                        },
                        new
                        {
                            ShopId = 3,
                            Goods = "third",
                            Name = "third shop",
                            Number = "goodbye c#"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
